FROM php:8.2-apache

# Устанавливаем расширения PHP для работы с MySQL
RUN docker-php-ext-install mysqli pdo_mysql

# Копируем файлы админки
COPY admin/ /var/www/html/

# Устанавливаем правильные права
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80

CMD ["apache2-foreground"]
